// <auto-generated />
namespace DataModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fix_relationship : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_relationship));
        
        string IMigrationMetadata.Id
        {
            get { return "202311161454536_fix_relationship"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
