// <auto-generated />
namespace DataModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class create_BlogCategories_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_BlogCategories_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "202310261443165_create_BlogCategories_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
