// <auto-generated />
namespace DataModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Intergrate_Aspnet_Identity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Intergrate_Aspnet_Identity));
        
        string IMigrationMetadata.Id
        {
            get { return "202310191613371_Intergrate_Aspnet_Identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
